.github/workflows/ci.yml
https://jira-eng-rtp3.cisco.com/jira/browse/LH-70127
There is no point running acceptance tests unles the unit tests pass, and we don't want to release if the unit tests pass. This makes the pipeline more serial.
=> ci(LH-70127): Do not run acceptance tests unless unit tests pass

.github/workflows/ci.yml
https://jira-eng-rtp3.cisco.com/jira/browse/LH-70319
Currently, we run the acceptance tests twice, once on a merge to main and then again when we create a tag to release the HEAD of main to the Terraform registry. This unnecessarily adds to the build time to release a new version of the terraform provider, as we essentially run the acceptance tests twice on each commit. With this commit, we will run the acceptance tests only on merge to main, and not when we tag a resource. When we tag a resource, we will proceed straight to releasing a new version of the provider to the Terraform registry.
=> ci(LH-70319): Run acceptance tests on merge to main, not on tag

.github/workflows/ci.yml
https://jira-eng-rtp3.cisco.com/jira/browse/LH-70586
Yesterday, I merged a PR (https://github.com/CiscoDevNet/terraform-provider-cdo/pull/45) where I removed the requirement to run acceptance tests when pushing a tag (having acceptance tests run only on merge to main). However, I failed in that PR to remove the dependency between the `acceptance-tests` job and the `release` job. In this PR, I fix that and add a dependency from unit-test to release instead.
=> ci(LH-70586): Ensure release task is run when tag is pushed

client/client.go, client/device/read_by_uid.go, provider/examples/data-sources/cdfmc/example.tf, provider/internal/cdfmc/data_source.go, provider/internal/cdfmc/data_source_test.go, provider/internal/provider/provider.go
https://jira-eng-rtp3.cisco.com/jira/browse/LH-70649
Add a cdFMC data source to the Terraform provider in order to get info from the FMC (hostname and software version to start with).
=> feat(LH-70649): Add cdFMC data source to the Terraform provider

client/client.go, provider/examples/data-sources/cdfmc/example.tf, provider/internal/cdfmc/data_source.go, provider/internal/cdfmc/data_source_test.go
https://jira-eng-rtp3.cisco.com/jira/browse/LH-70649
Also return the domain UUID when the cdFMC datasource is fetched
=> fix(LH-70649): Add the cdFMC domain UUID to list of data returned by the cdfmc data source

client/connector/bootstrapdata.go, client/internal/url/url.go, client/user/token.go, provider/examples/data-sources/cdfmc/example.tf, provider/examples/resources/ftd/aws_ftd.tf, provider/examples/resources/ftd/terraform.tfvars, provider/examples/resources/ftd/variables.tf, provider/examples/resources/sdc/sdc_example.tf, provider/examples/resources/user_api_token/example.tf
https://jira-eng-rtp3.cisco.com/jira/browse/LH-70915
There is an Anubis weirdness by which only a single token can exist for a given scope (external-compute and fmc tokens are exceptions we deliberately engineered to work around this limitation which is a feature of some kind). So when you call `/oauth/token` with the API token fed in to the Terraform provider, you actually get back the same token you called with. When this token is passed into the bootstrap function of our SDC, the bootstrap method revokes the token after setting up the SDC. This nvalidates the token the terraform-provider is using, and we end up having to regenerate the token. In this PR, I switch to using the external-compute token instead for bootstrapping the SDC. (yes, this is a hack, and no Weilue, we are not going …
=> fix(LH-70915): Use external-compute tokens to generate bootstrap data

client/device/asa/asafixture_test.go, client/device/asa/create.go, client/device/asa/create_test.go, client/device/create.go, client/device/genericssh/create.go, client/device/ios/create.go, client/model/featureflag/featureflag.go, client/model/user/auth/info.go, provider/examples/resources/asa/example.tf
https://jira-eng-rtp3.cisco.com/jira/browse/LH-69564
- Add read token before creating the ASA device to check whether tenant is using new ASA model.
- Add corresponding metadata field when creating the device
- Add test to check payload contains the right metadata when feature flag is set and vice versa.
=> feat(LH-69564): Supports ASA Onboarding Using New Model

.github/workflows/ci.yml
Siddhu mentioned Terraform 1.1 and 1.2 do not support a number of the AWS constructs we depend on to make stuff work in our labs; so there's no point supporting them.
=> Remove Support For Terraform Version <1.3 and add v1.5

client/connector/create.go, client/connector/create_test.go, client/connector/read.go, client/connector/readoutputbulider.go, provider/internal/connector/resource_test.go
https://jira-eng-rtp3.cisco.com/jira/browse/LH-72127
The SDC acceptance tests was leaking AWS SQS resource to be not deleted, because the test tear down too quickly, before the AWS SQS was ready, this PR waits for the queue to be ready during create operation.
I wanted to fix this in Aegis, but failed to find where to fix in Aegis so I just fix it here...
=> fix(LH-72127): SDC resource leak

client/connector/connectoronboarding/create.go, client/connector/create.go, client/device/asa/asaconfig/retry_test.go, client/device/asa/create.go, client/device/asa/update.go, client/device/cloudfmc/create.go, client/device/cloudfmc/fmcconfig/retry.go, client/device/cloudftd/cloudftdonboarding/create.go, client/device/cloudftd/create.go, client/device/cloudftd/delete.go, client/device/ios/create.go, client/device/ios/iosconfig/retry_test.go, client/internal/goutil/goutil.go, client/internal/http/request.go, client/internal/retry/do.go, client/internal/retry/do_test.go, client/internal/retry/error.go, provider/internal/device/ftd/resource.go
https://jira-eng-rtp3.cisco.com/jira/browse/LH-71921
Re-implement retry mechanism to consider the case of `context`, so that when `context` is cancelled, we stop retrying.
**Main files to look at**
- `client/internal/retry/do.go`
- `client/internal/retry/do_test.go`
- other files are just adding the `context` parameters
=> fix(LH-71921): Make use of context in retry function

.github/workflows/ci.yml, README.md
https://jira-eng-rtp3.cisco.com/jira/browse/LH-70847
This PR adds a job to the Github action workflow to create and push tag automatically on push into main branch and tests passes. Then it should trigger our already exist release job to actually do the release based on the new tag.
=> ci(LH-70847): automatically tag new version on push

.github/workflows/ci.yml
https://jira-eng-rtp3.cisco.com/jira/browse/LH-70847
Fix a typo that cause github action failed to run
=> ci(LH-70847): Fix github action trigger-release dependency

client/connector/readoutputbulider.go
https://jira-eng-rtp3.cisco.com/jira/browse/LH-72600
Changed 512 to 2048 to make CodeQL happy, it does not matter because it is used in unit test only.
See also: https://github.com/CiscoDevNet/terraform-provider-cdo/security/code-scanning/1
=> fix(LH-72600): Address CodeQL RSA bits min requirement

client/connector/create.go, client/connector/delete.go, client/connector/delete_test.go, client/internal/http/error.go, client/internal/http/request.go
https://jira-eng-rtp3.cisco.com/jira/browse/LH-72736
The root cause is unclear as I cant reproduce it consistently. The temporary fix is to keep trying delete until the backend does not return that connector anymore for GET request. Not entirely sure if this will fix it.
Also added ability to check for status code error that we are interested in.
=> fix(LH-72736): delete connector occasionally fails

provider/internal/device/ftd/configvalidator.go, provider/internal/device/ftd/resource.go
https://jira-eng-rtp3.cisco.com/jira/browse/LH-73329
**Given following FTD configuration** (`virtual` is true, but `performance_tier` is missing)
```
resource "cdo_ftd_device" "ftd" { 
name = "my-ftd" 
access_policy_name = "Default Access Control Policy"
virtual = true 
licenses = ["BASE"] 
}
```
=> fix(LH-73329): Fix error when create virtual FTD with no performance tier 

client/connector/read.go, client/device/cloudfmc/read.go, client/device/cloudftd/create.go, client/device/cloudftd/delete.go, client/device/cloudftd/delete_test.go, client/device/cloudftd/fixture_test.go, client/device/cloudftd/read_by_name.go, client/device/read_by_nameandtype.go, client/internal/statemachine/error.go, provider/internal/util/404error.go
https://jira-eng-rtp3.cisco.com/jira/browse/LH-73399
See the jira link above for an explanation of the bug. Basically what we need to do is to send the delete FTD object by UID after waiting for the FTD deletion state machine to finish (started by state=PENDING_DELETE_FTDC), instead of just waiting for it to start.
- Waited for the current deployment in the FTD to finish, otherwise the FTD deletion state machine will fail. To do this we need to:
- Read the FTD device record in FMC, to do this we need to:
- loop through all device records of the FMC because I did not find any parameter that allowed me to filter by device type / device name. To do this we need to:
- Read FMC domain info for its domain uid.
- Read FTD for its name to compare with the name in the FMC device records.
- Also …
=> fix(LH-73399): Correctly handle FTD deletion

client/model/ftd/license/license.go, provider/examples/resources/ftd/terraform.tfvars, provider/internal/device/ftd/operation.go, provider/internal/device/ftd/resource.go
https://jira-eng-rtp3.cisco.com/jira/browse/LH-73551
To reproduce the bug:
1. create a FTD in CDO with FMC license. (i.e. `URL` instead of `URLFilter`, `ESSENTIALS` instead of `BASE`)
2. apply (success)
3. apply again (unexpected changes from CDO license to FMC license)
This is because I store the state as CDO license, but I forget to change the input from FMC license to CDO license. So during the first apply, the FMC license is changed to the CDO license is stored in the state, the next time the user apply, terraform finds the plan has the FMC license which is different from the state, it prompts the user for change. Although technically it does not make a difference because the license will be converted into CDO license later on, but we should be having a `ModifyPlan` function that …
=> fix(LH-73551): FTD License Inconsistency

client/device/cloudftd/cloudftdonboarding/create.go
Output proper FTD name instead of wrong FMC name
=> fix: FTD duplication error message

client/client.go, client/internal/url/url.go, client/msp/tenants/delete.go, client/msp/tenants/delete_test.go, client/msp/tenants/models.go, client/msp/tenants/read.go, client/msp/users/delete.go, docs/resources/msp_managed_tenant.md, provider/internal/msp/msp_tenant/resource.go
https://jira-eng-rtp3.cisco.com/jira/browse/LH-87215
This is a faux deletion, as described in the documentation. It removes the tenant from the MSP
portal, but doesn't actually delete it from the database.
=> fix(lh-87215): allow deletion of MSP-managed tenants

provider/internal/msp/msp_tenant/resource.go
The tenant name validation is not working when we pass the name parameter as a var
https://jira-eng-rtp3.cisco.com/jira/browse/LH-###### (or Github issue ID)
=> fix(cisco-live-2024): remove tenant name validation
